[color-theme]
name = "Aswad"
color-preference = "dark"

[ui]
drop-shadow-width = 4

[color-theme.base]
black = "#212121"
blue = "#80c0ff"
cyan = "#57d9ce"
green = "#a6d982"
grey = "#3E3E3E"
magenta = "#C678DD"
orange = "#f29f76"
purple = "#bda1e6"
red = "#f27997"
white = "#CCCCCC"
yellow = "#e6d373"

[color-theme.ui]
"activity.background" = "$black"
"activity.current" = "$black"

"completion.background" = "$black"
"completion.current" = "#2C2C2C"

"editor.background" = "$black"
"editor.caret" = "#528BFF"
"editor.current_line" = "#2C2C2C"
"editor.dim" = "#5C5C5C"
"editor.drag_drop_background" = "#79797955"
"editor.drag_drop_tab_background" = "#0b0b0b55"
"editor.focus" = "#CCCCCC"
"editor.foreground" = "$white"
"editor.indent_guide" = "$grey"
"editor.link" = "$blue"
"editor.selection" = "$grey"
"editor.sticky_header_background" = "$black"
"editor.visible_whitespace" = "$grey"

"error_lens.error.background" = "#E06C7520"
"error_lens.error.foreground" = "$red"
"error_lens.other.background" = "#5C5C5C20"
"error_lens.other.foreground" = "#5C5C5C"
"error_lens.warning.background" = "#E5C07B20"
"error_lens.warning.foreground" = "$yellow"

"hover.background" = "$black"

"inlay_hint.background" = "#52525237"
"inlay_hint.foreground" = "$white"

"lapce.border" = "#000000"
"lapce.button.primary.background" = "#50a14f"
"lapce.button.primary.foreground" = "$black"
"lapce.dropdown_shadow" = "#000000"
"lapce.error" = "$red"
"lapce.icon.active" = "$white"
"lapce.icon.inactive" = "$5C5C5C"
"lapce.plugin.author" = "#B0B0B0"
"lapce.plugin.description" = "$white"
"lapce.plugin.name" = "#DDDDDD"
"lapce.remote.connected" = "#50A14F"
"lapce.remote.connecting" = "#C18401"
"lapce.remote.disconnected" = "#E45649"
"lapce.remote.local" = "#4078F2"
"lapce.scroll_bar" = "#grey"
"lapce.tab.active.background" = "#2C2C2C"
"lapce.tab.active.foreground" = "$white"
"lapce.tab.active.underline" = "#528BFF"
"lapce.tab.inactive.background" = "$black"
"lapce.tab.inactive.foreground" = "$white"
"lapce.tab.inactive.underline" = "#528BFF77"
"lapce.tab.separator" = ""
"lapce.warn" = "$yellow"

"markdown.blockquote" = "#898989"

"palette.background" = "$black"
"palette.current.background" = "#2C2C2C"
"palette.current.foreground" = "$white"
"palette.foreground" = "$white"
"panel.background" = "#161616"
"panel.current.background" = "#2C2C2C"
"panel.current.foreground" = "$white"
"panel.current.foreground.dim" = "#5C5C5C"
"panel.foreground" = "$white"
"panel.foreground.dim" = "#5C5C5C"
"panel.hovered.background" = "#343434"
"panel.hovered.foreground" = "$white"
"panel.hovered.foreground.dim" = "#5C5C5C"

"source_control.added" = "#50a14f32"
"source_control.modified" = "#0184bc32"
"source_control.removed" = "#ff526632"

"status.background" = "#161616"
"status.foreground" = "$white"
"status.modal.insert" = "$red"
"status.modal.normal" = "$blue"
"status.modal.terminal" = "$purple"
"status.modal.visual" = "$yellow"

"terminal.background" = "$black"
"terminal.black" = "#000000"
"terminal.blue" = "$blue"
"terminal.bright_black" = "#545454"
"terminal.bright_blue" = "$blue"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_green" = "$green"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_red" = "$red"
"terminal.bright_white" = "#C8C8C8"
"terminal.bright_yellow" = "$yellow"
"terminal.cursor" = "#white"
"terminal.cyan" = "$cyan"
"terminal.foreground" = "$white"
"terminal.green" = "$green"
"terminal.magenta" = "$magenta"
"terminal.red" = "$red"
"terminal.white" = "$white"
"terminal.yellow" = "$yellow"

[color-theme.syntax]
"attribute" = "$yellow"
"builtinType" = "$cyan"
"comment" = "#6A6A6A"
"constant" = "$green"
"constructor" = "$red"
"embedded" = "$cyan"
"enum" = "$yellow"
"enum-member" = "$red"
"enumMember" = "$red"
"escape" = "$cyan"
"field" = "$red"
"function" = "$blue"
"function.method" = "$blue"
"interface" = "$yellow"
"keyword" = "$orange"
"keyword.control" = "$purple"
"method" = "$blue"
"number" = "$yellow"
"property" = "$white"
"punctuation.delimiter" = "$white"
"selfKeyword" = "$purple"
"string" = "$green"
"string.escape" = "$cyan"
"struct" = "$yellow"
"structure" = "$yellow"
"symbol" = "$yellow"
"tag" = "$blue"
"text.reference" = "$yellow"
"text.title" = "$orange"
"text.uri" = "$cyan"
"type" = "$yellow"
"type.builtin" = "$cyan"
"typeAlias" = "$yellow"
"variable" = "$white"
"variable.other.member" = "$green"


