name = "aswad"
version = "0.2.0"
display-name = "Aswad"
author = "ahmrz"
description = "A dark theme for Lapce Editor"
icon = "aswad.png"
repository = "https://github.com/ahmrz/lapce-aswad"
color-themes = [
    "aswad.toml"
]
